### ISSUE TITLE
Ubuntu 18.04 QtQuick 2.2 not found

### ISSUE THREAD

**Issue by patond** [per-d/notesFromChordTexts#1]
This plugin looks as if its exactly what I'm looking for.  Unfortunately when I download and copy the qml file to my Documents/Musescore 2/Plugins folder as instructed MuseScore crashes as soon as I click on Plugin Manager.  I see the first line of code is Import QtQuick 2.2  and I'm pretty sure MuseScore crashes because QtQuick 2.2 isn't installed.  Can you help?  What packages do I need to install?

**Comment by per-d** [comment]
Unfortunately I don’t know about MuseScore  on Ubuntu. I did some googling:
https://musescore.org/en/node/281629#comment-885885
https://musescore.org/en/node/90516#comment-412756
https://musescore.org/sv/musescore-2-ubuntu-14.04-and-above
http://ubuntuhandbook.org/index.php/2018/04/how-to-install-musescore-2-2-1-in-ubuntu-18-0416-04-via-ppa/
https://musescore.org/en/node/274552

Hope some will help, and if it does please comment it here.

**Comment by per-d** [comment]
Don't know how to run it on Ubuntu, and got no more info from @patond
