### ISSUE TITLE
error "can't get tick..." due to key change in score

### ISSUE THREAD

**Issue by Bacchushlg** [per-d/notesFromChordTexts#2]
[Body_and_Soul.zip](https://github.com/per-d/notesFromChordTexts/files/3740266/Body_and_Soul.zip)

This file makes problem when running the plug-in due to a key chance in measure 17.
From then no more chords are generated.
Is there a possibility to ignore the warning and continue with the rest of the score?

**Comment by per-d** [comment]
Hello. I saw this now, I will look at it during the weekend.

**Comment by Bacchushlg** [comment]
Maybe I should tell you that I found a work-around: I simply added a line break in the measure before the critical one. This leads to a situation where the key change now happens in the note line - no more in the end.
This works.
But of course it would be nice to solve this "little" problem anyway.
For the rest I need to tell you that I use your plug-in rather often and it's almost perfect for me!
Thank you for this!

**Comment by per-d** [comment]
I have fixed it now, I have to figure out how to upload a new version though, haven't worked with GIT so much.
It takes time to fix problems in the code, I haven't a proper environment for the language so I can't use a step-by-step debugger. Perhaps there is none?

Glad someone is enjoing the plug-in!

**Comment by Bacchushlg** [comment]
I tried the version that you uploaded. Unfortunately the plug-in crashes when I try it with another score. But anyway the above problem is solved.
Thank you for this!

**Comment by per-d** [comment]
Can you upload the score that crashes? Perhaps in a new issue, then I can close this.
Did the other score crash also with the old version?

But first, have you tried:

## Known issues
(won't fix)  
- For some scores the plugin crashes. To avoid this, start the plugin with no score opened. Just click the shown error message and then open the score you want and run the plugin again. This "fix" will last for the whole MuseScore session.  
If the plugin still crashes even if this is done, then you can report that as an issue.

**Comment by Bacchushlg** [comment]
[Body and Soul (1).zip](https://github.com/per-d/notesFromChordTexts/files/3784922/Body.and.Soul.1.zip)

Here the score that makes MuseScore crash when I run your plugin

**Comment by per-d** [comment]
I tried it and it works if follow the below tip. BUT **you must open MuseScore alone, not open it by doubleclick any score file**. Then run the the plugin **before opening any score**, click OK on the error message. Then you can open your score and run the plugin.

I spent a lot of time trying to fix this issue when making the plugin, but I never managed to fix it. For some reason some scores acts like that.

From the README:

## Known issues
(won't fix)  
- For some scores the plugin crashes. To avoid this, start the plugin with no score opened. Just click the shown error message and then open the score you want and run the plugin again. This "fix" will last for the whole MuseScore session.  
If the plugin still crashes even if this is done, then you can report that as an issue.
