### ISSUE TITLE
chord symbol for major 7 (triangle) is not supported

### ISSUE THREAD

**Issue by Bacchushlg** [per-d/notesFromChordTexts#3]
major 7 chords can be notified with a "t" in MuseScore, leading to a displayed triangle.
Would be fine to support this in your script, too. Actually it creates a simple major chord with a hint "ignored: t".

**Comment by per-d** [comment]
Can you attach a simple score with examples with that notification?

**Comment by Bacchushlg** [comment]
[Begin The Beguine.zip](https://github.com/per-d/notesFromChordTexts/files/3747923/Begin.The.Beguine.zip)

no problem...

**Comment by per-d** [comment]
Thanks. It's fixed, I will upload a new version soon, where also issue #2 is fixed.

**Comment by per-d** [comment]
@Bacchushlg, I'm a noob on GitHub, I don't know if you received any notice of my commits automatically? However, I fixed both issues last weekend.
